bazzite-org/docs.bazzite.gg

src/General/Installation_Guide/dual_boot_setup_guide.md

Found a better tutorial video for manual partitioning, update the link to the better video

chore(docs): use better video for manual partition

---

README.md

* Fixed README.md dependency installation script
* Added section for running MKDocs locally in README.md

chore(docs): add local-dev instructions to docs

---

src/General/Installation_Guide/Installing_Bazzite_for_Desktop_or_Laptop_Hardware.md
src/General/Installation_Guide/Installing_Bazzite_for_HTPC_Setups.md

Add note about supported wifi adapters

---

src/Handheld_and_HTPC_edition/Handheld_Wiki/ASUS_ROG_Ally.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayaneo_Handhelds.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayn_Handhelds.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/GPD_Handhelds.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/Lenovo_Legion_Go.md

Link new contributing guide

---

src/General/Installation_Guide/dual_boot_setup_guide.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayaneo_Handhelds.md
src/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/bazzite_rollback_helper.md

A few things:
- add more emphasis to the separate EFI partition for dual boot setups
- add ayaneo wifi workaround
- add `bazzite-rollback-helper` example

A few doc fixes + improvements 

---

mkdocs.yml
src/Advanced/looking-glass.md

Added looking glass (dracut is next)

---

mkdocs.yml
src/Advanced/rescue-and-emergency-mode.md

Rescue emergency mode

---

src/Handheld_and_HTPC_edition/Handheld_Wiki/Lenovo_Legion_Go.md
src/Handheld_and_HTPC_edition/update-bios.md

Add BIOS update section for Legion Go (thanks mr fluffles!)

---

theme_overrides/main.html

Only merge after that link is public!

Add announcement about OneXPlayer handhelds

---

src/Gaming/Hardware_compatibility_for_gaming.md
src/General/Installation_Guide/Installing_Bazzite_for_Desktop_or_Laptop_Hardware.md

Add 64GB requirement to the rest of the pages

---

mkdocs.yml
src/Advanced/Auto-Mounting_Secondary_Drives.md
src/Gaming/Hardware_compatibility_for_gaming.md
src/General/Installation_Guide/dual_boot_setup_guide.md

a bunch of stuff pt. 1 (FAQ now in the navigation at top instead of in general)

---

404.md

Add 404 Page

---

mkdocs.yml
src/donations.md

Add Donations page

---

src/donations.md

Their contributions should be credited no matter how early into the Universal Blue or Bazzite project it was.

Add former contributors to the credits

---

theme_overrides/main.html

Add Bazzite 41 announcement banner

---

src/Handheld_and_HTPC_edition/Steam_Gaming_Mode.md

Add how to enable UI Scaling

---

src/Handheld_and_HTPC_edition/Steam_Gaming_Mode.md

add some small clarifications to the Internal Display scaling workaround
@nicknamenamenick

clarify workaround instructions for internal display scaling

---

src/General/Installation_Guide/alternate-install-guide.md
src/General/Installation_Guide/troubleshoot_guide.md

Separate rebase guide

---

src/Advanced/Auto-Mounting_Secondary_Drives.md
src/Advanced/Reset_Forgotten_User_Password.md
src/CONTRIBUTE.md
src/Gaming/index.md
src/General/Desktop_Environment_Tweaks.md
src/General/reporting_bugs.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/ASUS_ROG_Ally.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayaneo_Handhelds.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayn_Handhelds.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/GPD_Handhelds.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/Lenovo_Legion_Go.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/OneXPlayer_Handhelds.md

remove some view all docs (Not all)

---

src/Installing_and_Managing_Software/Quadlet.md

Apparently you dont need to run systemctl enable lol

Fix quadlet autostart documentation

---

src/General/Installation_Guide/Installing_Bazzite_for_Handheld_PCs.md

Fixed some grammatical issues

---

src/Installing_and_Managing_Software/Quadlet.md

I added few things such as:
- fix some inconsistencies
- added autostart to example quadlet
- added description for the key

Add additional docs in quadlet

---

src/donations.md

fix: jorge's title

---

src/Advanced/index.md
src/CONTRIBUTE.md
src/Gaming/Game_Launchers.md
src/General/Desktop_Environment_Tweaks.md
src/General/FAQ.md
src/General/Installation_Guide/Installing_Bazzite_for_Handheld_PCs.md
src/General/Installation_Guide/alternate-install-guide.md
src/General/Installation_Guide/troubleshoot_guide.md
src/General/index.md
src/General/issues_and_resolutions.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/ASUS_ROG_Ally.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayaneo_Handhelds.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayn_Handhelds.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/GPD_Handhelds.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/Lenovo_Legion_Go.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/OneXPlayer_Handhelds.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/Steam_Deck.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/index.md
src/Handheld_and_HTPC_edition/Steam_Gaming_Mode.md
src/Handheld_and_HTPC_edition/quirks.md
src/Installing_and_Managing_Software/index.md
src/Installing_and_Managing_Software/rpm-ostree.md
src/Installing_and_Managing_Software/ujust.md
src/donations.md

chore: Remove hardcoded urls.

---

.github/workflows/deploy_docs.yml
hooks/fail_on_hardcoded_url.py
mkdocs.yml
src/General/Installation_Guide/Installing_Bazzite_for_Desktop_or_Laptop_Hardware.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/index.md
src/Handheld_and_HTPC_edition/Steam_Gaming_Mode.md

Add a hook that throws an error whenever an hardcoded link is used.
Add enable docs bulding workflow to Pull Requests, to make it easier to detect possible issues before merging.
Plus replace some hardcoded links

feat(ci): Add hook for hardcoded URLs and update documentation links

---

src/General/FAQ.md
src/General/index.md

add navigation to the SteamOS Comparison, if you'd prefer to place it elsewhere please do

fix: steamos comparison navigation

---

src/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/rebase_guide.md

fixes the docs to get a list of stable images instead of empty list

fix: grep for searching stable images

---

src/General/SteamOS_Comparison.md

add mention of dual boot support in the SteamOS comparison

add dual boot support to steamos comparison doc

---

src/General/Installation_Guide/Installing_Bazzite_for_Handheld_PCs.md

update some stale links + change out the YT video link with an updated one

update links + update video to newer link from wolfy

---

src/Advanced/Reset_Forgotten_User_Password.md

Hi!
I recently followed this guide and wanted to offer some improvements to the wording and entering the GRUB menu.
Doesn't need saying but, of course, please feel free to edit or close.
Thanks so much for all the great docs on this project!

fix: Improve "Reset Forgotten User Password" Guide

---

src/Handheld_and_HTPC_edition/quirks.md

restore gamemode shortcut can be much more simple now:
https://github.com/ublue-os/bazzite/pull/2092
feel free to hold on this PR till changes go from testing into main!

feat: adjust restore game mode shortcut instructions per bazzite PR 2092

---

src/Installing_and_Managing_Software/ujust.md

Add documentation for common Bazzite ujust scripts

---

src/General/issues_and_resolutions.md

Add lag spikes fix for Rog Ally Z1E in issues and resolutions

---

src/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/updating_guide.md

Actual command is `ujust toggle-updates`

docs: Fixing typo in toggle-updates command

---

macros_tmpls/README.md
macros_tmpls/desktop_envs.md
mkdocs.yml
src/General/Installation_Guide/Installing_Bazzite_for_Desktop_or_Laptop_Hardware.md
src/General/Installation_Guide/Installing_Bazzite_for_HTPC_Setups.md
src/General/Installation_Guide/Installing_Bazzite_for_Handheld_PCs.md
src/General/Installation_Guide/Installing_Bazzite_for_Steam_Deck.md

Avoid duplication and future disparity between installation pages

refactor: Converge desktop environments overview into a single macro

---

src/General/issues_and_resolutions.md

I've tried this solution on a number of my Bazzite devices and it's reduced my wi-fi issues on all of them.
It was also the solution for this thread in the Bazzite help today
<https://discord.com/channels/1072614816579063828/1340469393649434754>

docs: cleanup Wi-Fi lag spikes solution

---

src/donations.md

Update Adelia's GitHub user to new name

---

mkdocs.yml
src/Advanced/scopebuddy.md

Unsure if there is anything else needed

Feat: add documentation for ScopeBuddy

---

src/Advanced/index.md

chore: add scopebuddy documentation to advanced index

---

src/Advanced/scopebuddy.md

chore: fix grammar

---

src/index.md

fix typo in contributing section

---

src/Advanced/scopebuddy.md

chore(scopebuddy): Use a more realistic example for appid config

---

src/Advanced/scopebuddy.md

fix: add some corrections to scopebuddy docs

---

src/General/Installation_Guide/dual_boot_setup_guide.md

update link to newer video from @wolfyreload

update dual boot link for manual partitioning

---

src/Installing_and_Managing_Software/Quadlet.md

Added samba as an example, also added the filepath in the example as comment.
Fixed some grammar.

Docs: added samba as quadlet example

---

mkdocs.yml
src/Dev/index.md

I really hope someone else can write more about this part of the project later.

Add developer eXperience inital documentation

---

src/Gaming/Game_Launchers.md

Extremely minor, but fixes the note saying "Fornite" instead of "For***t***nite".

fix Fornite typo

---

src/Gaming/Game_Launchers.md

Remove screenshot and instruction to enable UMU and apply known fixes.

Docs: Remove description for Heroic settings that are no longer present

---

src/General/Installation_Guide/Installing_Bazzite_Framework_Laptop_13.md
src/General/Installation_Guide/Installing_Bazzite_for_Framework_Laptop_16.md
src/index.md

This fixes search bar bringing you to a 404 page

fix: use js redirects for framework pages

---

mkdocs.yml
src/General/Fedora_Atomic_Comparison.md
src/General/index.md

Add a quick comparison between Bazzite and upstream Fedora Atomic

---

src/Installing_and_Managing_Software/Quadlet.md

Added notes about .container suffix and reloading after creating unit. Also added quadlet dryrun to find syntax mistake.

Docs: add more notes to quadlet page

---

src/Handheld_and_HTPC_edition/Handheld_Wiki/ASUS_ROG_Ally.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayaneo_Handhelds.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayn_Handhelds.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/GPD_Handhelds.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/Lenovo_Legion_Go.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/OneXPlayer_Handhelds.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/Other_Handhelds.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/Steam_Deck.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/index.md

@antheas DRAFT PR... go wild.  i'll help out when i can!  anyone else with write priv (or not), feel free to add suggestions here in the comments or edit the PR directly.
I'm removing the 'statuses' because i feel like known issues are more important than a useless status label.

Handheld wiki revamp (DRAFT)

---

src/Advanced/scopebuddy.md

feat: update scopebuddy docs with a script example

---

src/General/Installation_Guide/troubleshoot_guide.md

Add additional "code 1" error scenarios and workarounds

---

src/General/issues_and_resolutions.md

Add iwd issue resolutions

---

src/Installing_and_Managing_Software/ujust.md

fix(ujust): typo

---

src/Gaming/Hardware_compatibility_for_gaming.md

fix: remove mention of kde partition manager

---

src/Installing_and_Managing_Software/Quadlet.md

feat: added autoupdate key to quadlet

---

src/General/Desktop_Environment_Tweaks.md

@wolfyreload and @asen23 Please let me know if I should make any changes to this, thank you.

Add Wallpaper Engine back but with reset command

---

src/Installing_and_Managing_Software/AppImage.md

docs: tell user to install gearlever from store

---

src/General/zerotier.md

Hello. I was following this guide but it didn't work for me, so I found out the solution and wrote up this gist https://gist.github.com/adokitkat/63e704c1fc20de8aa0bff676af484924. Then I was like why not just fix the docs :)

fix: Fix missing or wrong info in zerotier.md

---

src/General/VPN.md

Fixing link in VPN guide.
