mkdocs.yml

* Link to "Auto-Mounting Secondary Drives" under the Advanced section in the documentation

chore(docs): add missing link to "Auto-Mounting Secondary Drives"

---

src/Handheld_and_HTPC_edition/Handheld_Wiki/index.md

* Adding section for how to install Decky in Bazzite since we have info on the Decky plugins but not Decky itself

chore(docs): Add Decky Setup section to Handheld wiki

---

src/Handheld_and_HTPC_edition/Steam_Gaming_Mode.md

Change the hotkey to open QAM from `ctrl + 2` to `super + 2` to reflect the change on https://github.com/ublue-os/bazzite/pull/1724.
We can merge it once v3.7.0 has been released.

Update Steam_Gaming_Mode.md for QAM hotkey change

---

.devcontainer/devcontainer.json

This will help us to avoid the "but it works in my machine".
Given universal blue heavily promotes containers, would make sense our
docs were to be built and developed with them.

feat: Add devcontainers

---

src/General/FAQ.md

Removed "bazzite-asus-deck" and "bazzite-asus-deck-gnome" images from the Bazzite Image List since these images do not exist in the list of downloadable/rebasable Bazzite images.

docs: remove images from image chart that don't exist

---

src/Advanced/GNOME_Disks_Auto-Mount_Guide.md
src/Advanced/KDE_Partition_Manager_Auto_Mount_Guide.md

Update NTFS to be more direct that Bazzite does not support NTFS no matter what it's use is.

Update NTFS note in Auto-Mount Guides

---

src/Advanced/Auto-Mounting_Secondary_Drives.md

you do not need a particular active working dir when using an absolute path in (the subsequent) command

docs: remove unnecessary command in Auto-Mounting_Secondary_Drives.md

---

src/General/SteamOS_Comparison.md
src/Handheld_and_HTPC_edition/Handheld_Wiki/Steam_Deck.md

moved the SteamOS comparison stuff to a dedicated page, not sure if there's a better location to put the document

feat: add dedicated steamOS comparison page

---

src/Advanced/swapfile.md

`sudo btrfs subvolume create /var/swap` seems to create the folder when it creates the subvolume, if you try and make the folder first you can't make the subvolume

docs: fixed error in hibernation guide

---

src/Handheld_and_HTPC_edition/Handheld_Wiki/Steam_Deck.md

Just a few OS-related issues that i've encountered with the Steam Deck OLED. unsure if they also happen with the LCD, but important to point out nonetheless.

docs: steamdeck: add list of known issues

---

src/donations.md

I've set a fixed width on the maintainers and contributors so they all equally sized and played a little bit with the line height. All the blocks are the same width and the page is still mobile friendly.
Page now looks like this
Rather than this

Improved css on Credits & Donating page

---

src/Installing_and_Managing_Software/Homebrew.md

We unlink the systemd and dbus parts of brew now so this is fine.

fix: update Homebrew.md

---

src/Advanced/scopebuddy.md

:wave:
This PR add some basic documentation for [features added to scopebuddy in this pull request](https://github.com/HikariKnight/ScopeBuddy/pull/1). If I'm understanding the way that scopebuddy is pulled into bazzite images correctly, this won't be updated until the next image release occurs, but I want to get the docs written up while it's all still fresh in my head :)

docs: add documentation for scopebuddy auto res/hdr/vrr args

---

macros_tmpls/automounting_guide_depr.md

Remove temporary outdated bits from auto-mounting guide.

Remove temporary stuff from automounting guide

---

src/General/Desktop_Environment_Tweaks.md

As talked about in [this convo](https://discord.com/channels/1072614816579063828/1237926270151688192/1372576370323882086) in the Universal Blue discord server.
The reason the themes are not shown in Discover is not related to the file system structure, but rather related with performance and KDE compatibility issues. This PR updates the docs to clarify this.
I added the note about potentially needing to manually uninstall themes because it seemed to be slightly glitched in not always allowing me to uninstall them; as far as I can tell, this is not a Bazzite issue, but rather some other KDE bug I have not fully debugged

Update paragraph regarding KDE themes and discover

---

macros_tmpls/installer_requirements.md

I know Bazzite doesn't support Mac hardware at the moment, but that doesn't mean people won't flash their usb from their Mac. For instance, I just had to because my Linux laptop won't boot.
Fedora Media Writer does support Intel/Arm Macs so I changed that link to indicate that. Unfortunately they don't sign their binaries so it's not beginner friendly: https://github.com/FedoraQt/MediaWriter/issues/710
I added a link to Belena Etcher, which has a great UI and works on macs. It is open source but at least at one point apparently tracked your data: https://www.gameindustry.eu/reviews/balenaetcher/
Nothing really is a perfect solution but I'm pretty sure some of the folks curious about Bazzite have a mac.

Add link for Balena Etcher

---

src/Advanced/swapfile.md

Best to habituate backing up before editing system configs.
Not entirely sure about zram-generator.conf -- IIRC the default /etc files should always be /usr/etc but I can't check on an actual install right now because I'm at work. Someone correct me if I'm wrong.

docs: Add instruction to backup fstab and how to restore zram-generator.conf

---

src/Installing_and_Managing_Software/index.md

ujust should be preferred over a flatpak. 
LACT as an example here: Won't function properly if just installing just the flatpak.

ujust should be preferred over a flatpak

---

src/General/FAQ.md

fix: typo in FAQ.md changed from "seperation" to "separation" in section "How is Fedora Atomic Desktop different than Fedora Workstation?"

fix: typo in FAQs

---

src/Installing_and_Managing_Software/Waydroid_Setup_Guide.md

Change the Android version notice to 13, add a section for the fake touch option.

docs: Update Waydroid Guide

---

src/Installing_and_Managing_Software/Waydroid_Setup_Guide.md

This PR adapts the Waydroid setup guide for Android 13. On Android 13, the default libhoudini used by waydroid-script does not exhibit performance problems with AMD CPUs. Additionally, libndk never had problems on Intel CPUs on any Android version. The recommendation for using libndk on AMD stems from libhoudini having better overall compatibility however some games run only on libndk.

docs: Waydroid Setup Guide corrections for translation layers

---

src/Advanced/plymouth_init.md

Updated  'Show  Detailed Init Logs During Boot' Wiki page with Better readability for people to not miss extra steps. (Better for people with limited technical info)

Update 'Show  Detailed Init Logs During Boot' ( plymouth_init.md ) Wiki Page for Better Readability for people with limited technical info

---

src/Resources.md

Feel free to also change this in a way that makes sense.  I just wanted to make sure that Discourse was no longer named 'forums'.

Reorganize social platforms page

---

src/Installing_and_Managing_Software/Homebrew.md

This page sometimes confuses people on the discord when a Linux compatible cask is recommended so clarify the situation a bit.

fix: Update the homebrew page with the information that there are casks that work on Linux
